### PR TITLE
Add python SDK manifest

### PR DESCRIPTION
**Pull request by AmirQSD**

### CODE REVIEW

**Review by QuintinWillison — APPROVED** [review]
Looks good to me, though I've not checked line by line against the Python codebase. I see that @owenpearson has kindly responded to @AmirQSD's [questions (internal Slack thread)](https://ably-real-time.slack.com/archives/C01C4TP3YBE/p1665748264410129?thread_ts=1665747986.640199&cid=C01C4TP3YBE), so it seems this pull request is in the correct state.

**Review by owenpearson — CHANGES_REQUESTED** [review]
Channel -> Status -> ChannelDetails is implemented in ably-python so we'll need to add that. Everything else LGTM 👍

**Comment by AmirQSD** [comment]
Added Channel -> Status -> ChannelDetails @owenpearson

**Review by owenpearson — APPROVED** [review]
LGTM, thanks

**Pull request merged**
