### PR TITLE
Php sdk manifest

### PR DESCRIPTION
**Pull request by AmirQSD**

### CODE REVIEW

**Review by QuintinWillison — APPROVED** [review]
I've not checked line-by-line against the PHP SDK, but looks sensible to me. Thanks! 😁

**Review by sacOO7 — APPROVED** [review]
LGTM : )

**Review by owenpearson — CHANGES_REQUESTED** [review]
A couple of things I think should be added:
- Opaque request - this is implemented in ably-php as `Rest.request` [source](https://github.com/ably/ably-php/blob/12345c7e6790e7dc0169e7505b0bea1a2e4b1241/src/AblyRest.php#L261-L271)
- Proxy - this appears to be implemented through the `http_proxy` environment variable [source](https://github.com/ably/ably-php/pull/51)

**Review by owenpearson — APPROVED** [review]
LGTM

**Pull request merged**
