### PR TITLE
Expand on `requires` - Feature Node Dependencies

### PR DESCRIPTION
**Pull request by QuintinWillison**
I've added some explanatory text around the use of the `requires` feature node property.

I've also added `REST` as a requirement to a few nodes that sit outside of the `REST` feature tree.

This thinking, plus prototyping, will help when working on https://github.com/ably/features/issues/64.

### CODE REVIEW

**Review by lmars — APPROVED** [review]

**Review by owenpearson — CHANGES_REQUESTED** [review]
A couple of things I notice looking at existing `.requires:` fields in `sdk.yaml`:

- The 'Environment' feature violates the 'cannot require one of its parent features' constraint.
- `REST Follows Realtime` has two dependencies specified by a yaml mutliline array and then wrapped in their own individual arrays. Not sure whether it still works or if this PR is the place to fix it but just so you're aware.

**Comment by QuintinWillison** [comment]
Thanks, @owenpearson ... I think once I clear up your observation around the YAML array embedding then that explains [the other two things that you notice](https://github.com/ably/features/pull/68#pullrequestreview-1130666024).

I extended the types of values that the `requires` property of a canonical feature node permits in https://github.com/ably/features/pull/67. I've done my best to articulate this a bit more clearly in https://github.com/ably/features/pull/68/commits/23915138993b80bd935660ca9255e1604a9ffd12. I've also added more unit tests in https://github.com/ably/features/pull/68/commits/329f0464aad5819a9b9f6f7172ee5f64cd51b66b to double check. 😁 

So, in respect of:

> `REST Follows Realtime` has two dependencies specified by a yaml mutliline array and then wrapped in their own individual arrays. Not sure whether it still works or if this PR is the place to fix it but just so you're aware.

It does work and is behaving how I intended it to. Because of the way that I've designed the `transformPaths` function to "do the right thing":

| Input | Output | Breakdown |
| ----- | ------ | ---- |
| `[['REST'], ['Realtime']]` | `[['REST'], ['Realtime']]` | **Correct**: Array containing two pointers (each an array containing a single element) to root feature nodes `REST` and `Realtime`. |
| `['REST', 'Realtime']` | `[['REST', 'Realtime']]` | **Incorrect**: Array containing a single pointer (itself an array) to `REST: Realtime`, which does not exist. |

And, in respect of:

> The 'Environment' feature violates the 'cannot require one of its parent features' constraint.

I think you're observing that the `Service: Environment` feature node `requires` the `Service: Fallbacks` node. If that is the case, then your analysis is incorrect according to my intentions for how that constraint should be interpreted, though you have got me doubting the way that I've worded it. 🤔 

These two feature nodes are siblings, so it _is_ appropriate that one of them may require the other.

My intention with the constraint was to describe that a feature can't require its direct parent node or any other parents of that node, up the family tree. So, it would not be valid for the `Service: Environment` node to `requires` the `Service` feature node because we know that already (it's implicit because it's a child of that node).

Could you perhaps suggest better wording for that constraint? I would happily add that to this PR.

**Comment by QuintinWillison** [comment]
I've just had a productive and detailed offline discussion with @owenpearson about his observations and my initial attempt to respond to them. I've been persuaded that representing pointers to feature nodes as arrays of strings makes the YAML difficult to interpret, especially given how `requires`' array interpretation is so different of that of the `specification` property values.

What I'm now going to do is refactor so that, in YAML form, pointers to feature nodes are always inputted as a single string using `': '` as the delimiter. So, where I currently have `['A', 'B', 'C']` it would now be `'A: B: C'`. This also matches the current 'to string' implementation I have in place for fully-qualified node name presentation.

I'm going to move this PR back to Draft state while I work on that.

**Review by owenpearson — APPROVED** [review]
Nice, LGTM! 😄

**Review by lmars — APPROVED** [review]

**Pull request merged**
